Practica_5/Practica_5/Controllers/ESTUDIANTEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica_5.Models;

namespace Practica_5.Controllers
{
    public class ESTUDIANTEsController : Controller
    {
        private UTILITIES_APPEntities db = new UTILITIES_APPEntities();
        [Authorize]
        public ActionResult Bienvenida()
        {
            return View();
        }

        // GET: ESTUDIANTES
        //Este Metodo Carga el Listado de Estudiantes Inscritos
        public ActionResult Consultar_Estudiantes()
        {
            return View(db.ESTUDIANTES.ToList());
        }
        //Este metodo mustras las Materias seleccionadas por el estudiante seleccionado(Valga la Redundancia)
        public ActionResult Mostrar_Materias(int? id_estudiante)
        {
            if(id_estudiante == null)
            {
                return RedirectToAction("Consultar_Estudiantes");
            }
            //La Variable lista_materias almacena una lista de todas las materias que tienen el id del estudiante seleccionado
            var materia_estudiantes = (from x in db.ESTUDIANTES_MATERIAS
                                       where x.ID_estudiante == id_estudiante
                                       select x);
           
          
            return View(materia_estudiantes);

        }
        public ActionResult Acerca_de()
        {
            return View();
        }

        ////// GET: ESTUDIANTEs/Details/5

        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: ESTUDIANTEs/Create
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID_estudiante,nombre,apellido,edad,sexo,carrera")] ESTUDIANTE eSTUDIANTE)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ESTUDIANTES.Add(eSTUDIANTE);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// POST: ESTUDIANTEs/Edit/5
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID_estudiante,nombre,apellido,edad,sexo,carrera")] ESTUDIANTE eSTUDIANTE)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(eSTUDIANTE).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// POST: ESTUDIANTEs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    db.ESTUDIANTES.Remove(eSTUDIANTE);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Practica_5/Practica_5/Controllers/EVENTOesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica_5.Models;

namespace Practica_5.Controllers
{
    public class EVENTOesController : Controller
    {
        private UTILITIES_APPEntities db = new UTILITIES_APPEntities();
        [Authorize]
        // GET: EVENTOes
        public ActionResult Index()
        {
            return View(db.EVENTOS.ToList());
        }
        [HttpPost]
        public ActionResult Index(string EVENTO)
        {


            var lista = from x in db.EVENTOS
                        select x;


            if (string.IsNullOrEmpty(EVENTO))
            {
                return View(db.CONTACTOes.ToList());
            }


            else
            {
                lista = lista.Where(a => a.descripcion.Contains(EVENTO));
                return View(lista);
            }


        }

        // GET: EVENTOes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // GET: EVENTOes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EVENTOes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_evento,fecha,hora,descripcion")] EVENTO eVENTO)
        {
            if (ModelState.IsValid)
            {
                db.EVENTOS.Add(eVENTO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eVENTO);
        }

        // GET: EVENTOes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // POST: EVENTOes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_evento,fecha,hora,descripcion")] EVENTO eVENTO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eVENTO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eVENTO);
        }

        // GET: EVENTOes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // POST: EVENTOes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EVENTO eVENTO = db.EVENTOS.Find(id);
            db.EVENTOS.Remove(eVENTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practica_5/Practica_5/Views/EVENTOes/Create.cshtml
@model Practica_5.Models.EVENTO

@{
    ViewBag.Title = "Create";
}

<h2>REGISTRO DE EVENTOS</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { placeholder = "MM/DD/YYYY", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora, new { htmlAttributes = new { placeholder = "00-00 PM O AM", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { placeholder = "ACTIVIDAD", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CREAR EVENTO" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-info" onclick="location.href=('@Url.Action("Index","EVENTOes")')">VOLVER ATRAS</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practica_5/Practica_5/Views/EVENTOes/Delete.cshtml
@model Practica_5.Models.EVENTO

@{
    ViewBag.Title = "Delete";
}


<br />
<h3>CONFIRME ANTES DE ELIMINAR</h3>
<strong>"NO HAY RECUPERACION DE DATOS"</strong>
<br />
<br />

<div class="panel-danger">
    <div class="panel-heading">EVENTO A ELIMINAR</div>
    <div class="panel-body">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.fecha)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hora)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hora)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

        </dl>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="ELIMINAR EVENTO" class="btn btn-danger btn-sm" />
            </div>
        }
        <div>
            <br />
            <button class="btn btn-info" onclick="location.href=('@Url.Action("Index","EVENTOes")')">VOLVER ATRAS</button>
        </div>
    </div>

</div>

Practica_5/Practica_5/Views/EVENTOes/Details.cshtml
@model Practica_5.Models.EVENTO

@{
    ViewBag.Title = "Details";
}
<br />
<h2>DETALLES</h2>
<br />
<br />
<brs />


<div class="panel-success">
    <div class="panel-heading">DETALLES DEL EVENTO</div>
    <div class="panel-body">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.fecha)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hora)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hora)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

        </dl>

    </div>
</div>
<p>
    @Html.ActionLink("EDITAR", "Edit", new { id = Model.ID_evento }, new { @class = "btn btn-warning" })
</p>
<p>
    <div>

        <button class="btn btn-info" onclick="location.href=('@Url.Action("Index","EVENTOes")')">VOLVER ATRAS</button>
    </div>
</p>

Practica_5/Practica_5/Views/EVENTOes/Edit.cshtml
@model Practica_5.Models.EVENTO

@{
    ViewBag.Title = "Edit";
}

<h2>EDITAR EVENTO REGISTRADO</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_evento)

        <div class="form-group">
            <label class="control-label col-md-2">Fecha-Evento</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Hora</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Descripcion del Evento</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="GUARDAR" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-info" onclick="location.href=('@Url.Action("Index","EVENTOes")')">VOLVER ATRAS</button>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practica_5/Practica_5/Views/EVENTOes/Index.cshtml
@model IEnumerable<Practica_5.Models.EVENTO>

@{
    ViewBag.Title = "Index";
}

<br />
<h2>EVENTOS REGISTRADOS</h2>
<br />
<br />
<label>BUSCAR MEDIANTE EVENTO O DESCRIPCION</label>
<form method="post">
    <input type="text" name="EVENTO" />
    <input type="submit" value="BUSCAR" placeholder="mm/dd/yyyy" />
</form>
<br />



<div class="panel-success">
    <div class="panel-heading">EVENTOS GUARDADOS</div>
    <div class="panel-body">


        <table class="table">
            <tr>
                <th>
                    <label>FECHA DE EVENTO</label>
                </th>
                <th>
                    <label>HORA</label>
                </th>
                <th>
                    <label>DESCRIPCION DEL EVENTO</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.hora)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    <td>
                        @Html.ActionLink("EDITAR", "Edit", new { id = item.ID_evento }, new { @class = "btn btn-warning btn-xs" })
                    </td>
                    <td>
                        @Html.ActionLink("DETALLES", "Details", new { id = item.ID_evento }, new { @class = "btn btn-info btn-xs" })
                    <td>
                    <td>
                        @Html.ActionLink("BORRAR", "Delete", new { id = item.ID_evento }, new { @class = "btn btn-danger btn-xs" })
                    </td>

                </tr>
            }

        </table>
    </div>
</div>


<p>
    <button class="btn btn-success" onclick="location.href=('@Url.Action("Create","EVENTOes")')">CREAR EVENTO</button>
</p>
<p>
    <button class="btn btn-primary" onclick="location.href=('@Url.Action("Bienvenida","ESTUDIANTEs")')">VOLVER ATRAS</button>
</p>