Practica_5/Practica_5/Models/ESTUDIANTE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.ESTUDIANTES_MATERIAS = new HashSet<ESTUDIANTES_MATERIAS>();
        }
    
        public int ID_estudiante { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Display(Name = "Edad")]
        public Nullable<int> edad { get; set; }
        [Display(Name = "Genero")]
        public string sexo { get; set; }
        [Display(Name = "Carrera")]
        public string carrera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTES_MATERIAS> ESTUDIANTES_MATERIAS { get; set; }
    }
}

Practica_5/Practica_5/Controllers/CONTACTOesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica_5.Models;

namespace Practica_5.Controllers
{
    public class CONTACTOesController : Controller
    {
    
        private UTILITIES_APPEntities db = new UTILITIES_APPEntities();
        [Authorize]
        // GET: CONTACTOes
        public ActionResult Index()
        {
            return View(db.CONTACTOes.ToList());
        }

        [HttpPost]
        public ActionResult Index(string Telbusqueda, string Nombusqueda)
        {


            var lista = from x in db.CONTACTOes
                        select x;
            var lista2 = from y in db.CONTACTOes
                         select y;

            if (string.IsNullOrEmpty(Telbusqueda) && string.IsNullOrEmpty(Nombusqueda))
            {
                return View(db.CONTACTOes.ToList());
            }
            else if (Nombusqueda != null)
            {
                lista2 = lista2.Where(a => a.nombre.Contains(Nombusqueda));
                return View(lista2);

            }

            else
            {
                lista = lista.Where(a => a.celular.Contains(Telbusqueda));
                return View(lista);
            }


        }

        // GET: CONTACTOes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTACTO cONTACTO = db.CONTACTOes.Find(id);
            if (cONTACTO == null)
            {
                return HttpNotFound();
            }
            return View(cONTACTO);
        }

        // GET: CONTACTOes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CONTACTOes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_contacto,nombre,celular,email,direccion")] CONTACTO cONTACTO)
        {
            if (ModelState.IsValid)
            {
                db.CONTACTOes.Add(cONTACTO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cONTACTO);
        }

        // GET: CONTACTOes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTACTO cONTACTO = db.CONTACTOes.Find(id);
            if (cONTACTO == null)
            {
                return HttpNotFound();
            }
            return View(cONTACTO);
        }

        // POST: CONTACTOes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_contacto,nombre,celular,email,direccion")] CONTACTO cONTACTO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cONTACTO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cONTACTO);
        }

        // GET: CONTACTOes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTACTO cONTACTO = db.CONTACTOes.Find(id);
            if (cONTACTO == null)
            {
                return HttpNotFound();
            }
            return View(cONTACTO);
        }

        // POST: CONTACTOes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CONTACTO cONTACTO = db.CONTACTOes.Find(id);
            db.CONTACTOes.Remove(cONTACTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Importar()
        {
            return View(new List<CustomerModel>());
        }

        [HttpPost]
        public ActionResult Importar(HttpPostedFileBase postedFile, string path)
        {
            List<CustomerModel> customers = new List<CustomerModel>();

            string filePath = string.Empty;
            if (postedFile != null)
            {
                path = Server.MapPath("~/Uploads/" + postedFile.FileName);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filePath);

                string csvData = System.IO.File.ReadAllText(filePath);

                foreach (string row in csvData.Split('\n'))
                {

                    if (!string.IsNullOrEmpty(row))
                    {
                        customers.Add(new CustomerModel
                        {

                            ID = int.Parse(row.Split(',')[0].ToString().Replace("-", " ").Trim()),
                            Nombre = row.Split(',')[1],
                            Apellido = row.Split(',')[2],
                            Telefono = row.Split(',')[3],
                            Direccion = row.Split(',')[4],
                            Edad = int.Parse(row.Split(',')[5].ToString().Replace("-", " ").Trim()),
                            Sexo = row.Split(',')[6]

                        }); ;

                    }
                }
            }
            return View(customers);
        }

    }
}

Practica_5/Practica_5/Controllers/ESTUDIANTEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica_5.Models;

namespace Practica_5.Controllers
{
    public class ESTUDIANTEsController : Controller
    {
        private UTILITIES_APPEntities db = new UTILITIES_APPEntities();
        [Authorize]
        public ActionResult Bienvenida()
        {
            return View();
        }

        // GET: ESTUDIANTES
        //Este Metodo Carga el Listado de Estudiantes Inscritos
        public ActionResult Consultar_Estudiantes()
        {
            return View(db.ESTUDIANTES.ToList());
        }
        //Este metodo mustras las Materias seleccionadas por el estudiante seleccionado(Valga la Redundancia)
        public ActionResult Mostrar_Materias(int? id_estudiante)
        {
            if(id_estudiante == null)
            {
                return RedirectToAction("Consultar_Estudiantes");
            }
            //La Variable lista_materias almacena una lista de todas las materias que tienen el id del estudiante seleccionado
            var materia_estudiantes = (from x in db.ESTUDIANTES_MATERIAS
                                       where x.ID_estudiante == id_estudiante
                                       select x);
           
          
            return View(materia_estudiantes);

        }
        public ActionResult Acerca_de()
        {
            return View();
        }

        ////// GET: ESTUDIANTEs/Details/5

        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: ESTUDIANTEs/Create
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID_estudiante,nombre,apellido,edad,sexo,carrera")] ESTUDIANTE eSTUDIANTE)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ESTUDIANTES.Add(eSTUDIANTE);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// POST: ESTUDIANTEs/Edit/5
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID_estudiante,nombre,apellido,edad,sexo,carrera")] ESTUDIANTE eSTUDIANTE)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(eSTUDIANTE).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// GET: ESTUDIANTEs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    if (eSTUDIANTE == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSTUDIANTE);
        //}

        //// POST: ESTUDIANTEs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ESTUDIANTE eSTUDIANTE = db.ESTUDIANTES.Find(id);
        //    db.ESTUDIANTES.Remove(eSTUDIANTE);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Practica_5/Practica_5/Controllers/EVENTOesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica_5.Models;

namespace Practica_5.Controllers
{
    public class EVENTOesController : Controller
    {
        private UTILITIES_APPEntities db = new UTILITIES_APPEntities();
        [Authorize]
        // GET: EVENTOes
        public ActionResult Index()
        {
            return View(db.EVENTOS.ToList());
        }
        [HttpPost]
        public ActionResult Index(string EVENTO)
        {


            var lista = from x in db.EVENTOS
                        select x;


            if (string.IsNullOrEmpty(EVENTO))
            {
                return View(db.CONTACTOes.ToList());
            }


            else
            {
                lista = lista.Where(a => a.descripcion.Contains(EVENTO));
                return View(lista);
            }


        }

        // GET: EVENTOes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // GET: EVENTOes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EVENTOes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_evento,fecha,hora,descripcion")] EVENTO eVENTO)
        {
            if (ModelState.IsValid)
            {
                db.EVENTOS.Add(eVENTO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eVENTO);
        }

        // GET: EVENTOes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // POST: EVENTOes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_evento,fecha,hora,descripcion")] EVENTO eVENTO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eVENTO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eVENTO);
        }

        // GET: EVENTOes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EVENTO eVENTO = db.EVENTOS.Find(id);
            if (eVENTO == null)
            {
                return HttpNotFound();
            }
            return View(eVENTO);
        }

        // POST: EVENTOes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EVENTO eVENTO = db.EVENTOS.Find(id);
            db.EVENTOS.Remove(eVENTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practica_5/Practica_5/Views/ESTUDIANTEs/Bienvenida.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <div class="jumbotron">
            <center>
                <h1>UTILITIES APP</h1>
            </center>
            <center>
                <p class="lead">Utilities App es una aplicacion web con que ofrece varias funcionalidades, como agenda, calendario de eventos, consulta de materias y lector archivos de Excel.</p>
                <p><a href="/Account/Register" class="btn btn-primary">¡Inicia Ahora!</a></p>
            </center>
        </div>

        <div class="row">
            <div class="col-md-3">
                <h3>Consulta de Materias</h3>
                <p>
                    Un formulario donde se elija el miembro del grupo a consultar y que muestre las asignaturas dicho miembro del grupo está cursando este cuatrimestre.
                </p>
                <center>
                    <a href="/ESTUDIANTEs/Consultar_Estudiantes" class="btn btn-primary">Realizar Consulta</a>
                </center>
            </div>

            <div class="col-md-3">
                <h3>Agenda electrónica</h3>
                <p>Podremos ver los contactos guardados en nuestra agenta, editarlos, eliminarlos y filtrarlos por Nombre o Numero de celular</p>
                <center>
                    <button class="btn btn-primary" onclick="location.href=('@Url.Action("index","CONTACTOes")')">IR A CONTACTOS</button>
                </center>
            </div>

            <div class="col-md-3">
                <h3>Calendario de Eventos</h3>
                <p>Podremos Registrar nuestros eventos para tenerlos pendientes y nunca perder ninguno.</p>
                <center>
                    <button class="btn btn-info" onclick="location.href=('@Url.Action("Index","EVENTOes")')">IR A EVENTOS</button>
                </center>
            </div>

            <div class="col-md-3">
                <h3>Lector de Archivos</h3>
                <p>Puede seleccionar un archivo de Excel para verificar su contenido.</p>
                <center>
                    <button class="btn btn-primary" onclick="location.href=('@Url.Action("Importar","CONTACTOes")')">IMPORTAR CONTACTOS</button>
                </center>
            </div>
        </div>
    </body>
</html>

Practica_5/Practica_5/Views/ESTUDIANTEs/Consultar_Estudiantes.cshtml
@model IEnumerable<Practica_5.Models.ESTUDIANTE>

<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <style>
        .tabla {
            background-color: white;
            color: black;
            font-family: 'Roboto', sans-serif;
        }
        .td{
            font-family: 'Roboto', sans-serif;
        }
        h2.{
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
<body>
    @*<p>
            @Html.ActionLink("Create New", "Create")
        </p>*@
    <center>
        <h2 class="text-center">Lista de Estudiantes</h2>
    </center>
    <div class="table-responsive">
        <table class="table table-sm tabla-dark ">
            <thead class="tabla">
                <tr>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.apellido)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.edad)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.sexo)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.carrera)
                    </th>
                    <th class="tabla">

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="tabla">
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.edad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.sexo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.carrera)
                        </td>
                        <td>
                            @Html.ActionLink("Verificar Materias", "Mostrar_Materias", new { id_estudiante = item.ID_estudiante }, htmlAttributes: new { @class = "btn btn-success" })
                            @*@Html.ActionLink("Edit", "Edit", new { id=item.ID_estudiante }) |
                                @Html.ActionLink("Details", "Details", new { id=item.ID_estudiante }) |
                                @Html.ActionLink("Delete", "Delete", new { id=item.ID_estudiante })*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Practica_5/Practica_5/Views/ESTUDIANTEs/Mostrar_Materias.cshtml
@model IEnumerable<Practica_5.Models.ESTUDIANTES_MATERIAS>

<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <style>
        .tabla {
            background-color: white;
            color: black;
            font-family: 'Roboto', sans-serif;
        }

        .td {
            font-family: 'Roboto', sans-serif;
        }

        .h3{
            font-family: 'Roboto', sans-serif;
        }
        .p{
            font-family: 'Roboto', sans-serif;
            font-size: 25px;
        }
    </style>
</head>
<body>
    <center>
        <h3>Lista de Materias Seleccionadas</h3>
    </center>
    <h4>
        @foreach (var bnombre in Model)
        {
            @Html.DisplayFor(model => bnombre.ESTUDIANTE.nombre) <label> </label>
            @Html.DisplayFor(model2 => bnombre.ESTUDIANTE.apellido)
            var contar = 1;
            if(contar == 1)
            {
                break;
            }
        }
    </h4>
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="tabla">
                <tr>
                    @*<th>
                        @Html.DisplayNameFor(model => model.ESTUDIANTE.nombre)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.MATERIA.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MATERIA.descripcion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MATERIA.horario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MATERIA.creditos)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MATERIA.profesor)
                    </th>
                </tr>
            </thead>
            <tbody>
              @foreach (var item in Model)
               {
                    <tr>
                        @*<td>
                             @Html.DisplayFor(modelItem => item.ESTUDIANTE.nombre)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.MATERIA.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MATERIA.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MATERIA.horario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MATERIA.creditos)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MATERIA.profesor)
                        </td>
                        @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID_estudiante_materia }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID_estudiante_materia }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID_estudiante_materia })
                        </td>*@
                    </tr>
                }
            </tbody>
        </table>
    <a class="btn btn-danger" href="/ESTUDIANTEs/Consultar_Estudiantes">Volver a la Lista de Estudiantes</a>
    </div>
</body>
</html>